/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SStructureIdRouteImport } from './routes/s.$structureId'
import { Route as EIdRouteImport } from './routes/e.$id'

const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SStructureIdRoute = SStructureIdRouteImport.update({
  id: '/s/$structureId',
  path: '/s/$structureId',
  getParentRoute: () => rootRouteImport,
} as any)
const EIdRoute = EIdRouteImport.update({
  id: '/e/$id',
  path: '/e/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/e/$id': typeof EIdRoute
  '/s/$structureId': typeof SStructureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/e/$id': typeof EIdRoute
  '/s/$structureId': typeof SStructureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/e/$id': typeof EIdRoute
  '/s/$structureId': typeof SStructureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/e/$id' | '/s/$structureId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/e/$id' | '/s/$structureId'
  id: '__root__' | '/' | '/calendar' | '/e/$id' | '/s/$structureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  EIdRoute: typeof EIdRoute
  SStructureIdRoute: typeof SStructureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$structureId': {
      id: '/s/$structureId'
      path: '/s/$structureId'
      fullPath: '/s/$structureId'
      preLoaderRoute: typeof SStructureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$id': {
      id: '/e/$id'
      path: '/e/$id'
      fullPath: '/e/$id'
      preLoaderRoute: typeof EIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  EIdRoute: EIdRoute,
  SStructureIdRoute: SStructureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
