/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagIdRouteImport } from './routes/tag.$id'
import { Route as SStructureTypeRouteImport } from './routes/s.$structureType'
import { Route as EIdRouteImport } from './routes/e.$id'

const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagIdRoute = TagIdRouteImport.update({
  id: '/tag/$id',
  path: '/tag/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SStructureTypeRoute = SStructureTypeRouteImport.update({
  id: '/s/$structureType',
  path: '/s/$structureType',
  getParentRoute: () => rootRouteImport,
} as any)
const EIdRoute = EIdRouteImport.update({
  id: '/e/$id',
  path: '/e/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/e/$id': typeof EIdRoute
  '/s/$structureType': typeof SStructureTypeRoute
  '/tag/$id': typeof TagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/e/$id': typeof EIdRoute
  '/s/$structureType': typeof SStructureTypeRoute
  '/tag/$id': typeof TagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/e/$id': typeof EIdRoute
  '/s/$structureType': typeof SStructureTypeRoute
  '/tag/$id': typeof TagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/e/$id' | '/s/$structureType' | '/tag/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/e/$id' | '/s/$structureType' | '/tag/$id'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/e/$id'
    | '/s/$structureType'
    | '/tag/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  EIdRoute: typeof EIdRoute
  SStructureTypeRoute: typeof SStructureTypeRoute
  TagIdRoute: typeof TagIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$id': {
      id: '/tag/$id'
      path: '/tag/$id'
      fullPath: '/tag/$id'
      preLoaderRoute: typeof TagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$structureType': {
      id: '/s/$structureType'
      path: '/s/$structureType'
      fullPath: '/s/$structureType'
      preLoaderRoute: typeof SStructureTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$id': {
      id: '/e/$id'
      path: '/e/$id'
      fullPath: '/e/$id'
      preLoaderRoute: typeof EIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  EIdRoute: EIdRoute,
  SStructureTypeRoute: SStructureTypeRoute,
  TagIdRoute: TagIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
